const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");

const generatePDF = async (req, res) => {
  try {
    const { title, content, topic } = req.body;

    if (!content || !title) {
      return res.status(400).json({ error: "Title and content are required" });
    }

    // Create PDF document
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const pageWidth = 612;
    const pageHeight = 792;
    const margin = 60;
    const contentWidth = pageWidth - margin * 2;

    // ─────────────────────────────────────────
    // Helper — add new page
    // ─────────────────────────────────────────
    const addPage = () => {
      const page = pdfDoc.addPage([pageWidth, pageHeight]);
      return { page, y: pageHeight - margin };
    };

    // ─────────────────────────────────────────
    // Helper — wrap text into lines
    // ─────────────────────────────────────────
    const wrapText = (text, fontSize, maxWidth) => {
      const words = text.split(" ");
      const lines = [];
      let currentLine = "";

      for (const word of words) {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        const width = font.widthOfTextAtSize(testLine, fontSize);
        if (width > maxWidth && currentLine) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine) lines.push(currentLine);
      return lines;
    };

    // ─────────────────────────────────────────
    // Cover page
    // ─────────────────────────────────────────
    let { page, y } = addPage();

    // Background header bar
    page.drawRectangle({
      x: 0,
      y: pageHeight - 200,
      width: pageWidth,
      height: 200,
      color: rgb(0.1, 0.1, 0.5),
    });

    // Title on cover
    const titleFontSize = 28;
    const titleLines = wrapText(title, titleFontSize, contentWidth);
    let titleY = pageHeight - 100;

    for (const line of titleLines) {
      const titleWidth = boldFont.widthOfTextAtSize(line, titleFontSize);
      page.drawText(line, {
        x: (pageWidth - titleWidth) / 2,
        y: titleY,
        size: titleFontSize,
        font: boldFont,
        color: rgb(1, 1, 1),
      });
      titleY -= titleFontSize + 8;
    }

    // Subtitle
    const subtitle = `Generated by NxtAI`;
    const subtitleWidth = font.widthOfTextAtSize(subtitle, 12);
    page.drawText(subtitle, {
      x: (pageWidth - subtitleWidth) / 2,
      y: pageHeight - 175,
      size: 12,
      font,
      color: rgb(0.8, 0.8, 0.9),
    });

    // Date
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const dateWidth = font.widthOfTextAtSize(date, 11);
    page.drawText(date, {
      x: (pageWidth - dateWidth) / 2,
      y: pageHeight - 230,
      size: 11,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });

    // ─────────────────────────────────────────
    // Content pages
    // ─────────────────────────────────────────
    let currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
    let currentY = pageHeight - margin;

    // Page header line
    const drawPageHeader = (pg) => {
      pg.drawRectangle({
        x: 0,
        y: pageHeight - 45,
        width: pageWidth,
        height: 45,
        color: rgb(0.95, 0.95, 0.98),
      });
      pg.drawText(title.slice(0, 60), {
        x: margin,
        y: pageHeight - 28,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
    };

    drawPageHeader(currentPage);
    currentY = pageHeight - 70;

    // Parse and render content sections
    const sections = content.split("\n\n").filter(Boolean);

    for (const section of sections) {
      const lines = section.split("\n").filter(Boolean);

      for (const line of lines) {
        const isHeading = line.startsWith("##") || line.startsWith("#");
        const isBullet = line.startsWith("-") || line.startsWith("•");

        const cleanLine = line
          .replace(/^#+\s*/, "")
          .replace(/^[-•]\s*/, "")
          .replace(/\*\*/g, "")
          .trim();

        if (!cleanLine) continue;

        const fontSize = isHeading ? 16 : 11;
        const usedFont = isHeading ? boldFont : font;
        const color = isHeading ? rgb(0.1, 0.1, 0.5) : rgb(0.15, 0.15, 0.15);
        const lineSpacing = isHeading ? 24 : 16;
        const leftX = isBullet ? margin + 15 : margin;

        // Space before headings
        if (isHeading) currentY -= 10;

        const wrappedLines = wrapText(
          cleanLine,
          fontSize,
          contentWidth - (isBullet ? 15 : 0),
        );

        for (let i = 0; i < wrappedLines.length; i++) {
          // New page if needed
          if (currentY < margin + 40) {
            currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
            drawPageHeader(currentPage);
            currentY = pageHeight - 70;
          }

          // Bullet dot
          if (isBullet && i === 0) {
            currentPage.drawCircle({
              x: margin + 5,
              y: currentY + 3,
              size: 2.5,
              color: rgb(0.1, 0.1, 0.5),
            });
          }

          currentPage.drawText(wrappedLines[i], {
            x: leftX,
            y: currentY,
            size: fontSize,
            font: usedFont,
            color,
          });

          currentY -= lineSpacing;
        }

        // Space after headings
        if (isHeading) currentY -= 6;
      }

      currentY -= 10; // Space between sections
    }

    // ─────────────────────────────────────────
    // Page numbers on all pages except cover
    // ─────────────────────────────────────────
    const pages = pdfDoc.getPages();
    for (let i = 1; i < pages.length; i++) {
      const pg = pages[i];
      const pageNum = `${i} / ${pages.length - 1}`;
      const numWidth = font.widthOfTextAtSize(pageNum, 10);
      pg.drawText(pageNum, {
        x: (pageWidth - numWidth) / 2,
        y: 30,
        size: 10,
        font,
        color: rgb(0.6, 0.6, 0.6),
      });
    }

    // Serialize PDF
    const pdfBytes = await pdfDoc.save();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${title.slice(0, 30).replace(/\s+/g, "_")}.pdf"`,
    );
    res.send(Buffer.from(pdfBytes));
  } catch (error) {
    console.error("generatePDF error:", error.message);
    res.status(500).json({ error: "PDF generation failed" });
  }
};

module.exports = { generatePDF };
